### ISSUE TITLE
В названии файла весь путь до него.

### ISSUE THREAD

**Issue by maks2027** [1C-Connect/1cconnect-text-bot#13]
Здравствуйте.
Если прикрепить файл (например pdf) то пользователь увидит вместо одного названия весь путь до него.

Пример:
Файл хранится в: chat_bot/exaples/exaple.pdf тогда клиент такое и название и уведет "chat_bot/exaples/exaple.pdf", ожидается что  у клиента в 1c connect будет просто "exaple.pdf".

**Comment by LilKirill00** [comment]
Здравствуйте, данная проблема уже известна и отправлена на слияние https://github.com/1C-Connect/1cconnect-text-bot/pull/11/commits/c8bfad0f96ed53fe192aa35f3749e68f9910af44
